### ISSUE TITLE
Algolia search not working in v2

### ISSUE THREAD

**Issue by Levdbas** [timber/docs#64]
**Bug description**

Algolia search is not working in the v2 docs. I was not able to find out why unfortunately. :(

**Comment by gchtr** [comment]
@Levdbas Thanks for flagging this! I found the issue and resolved it.

Some background: We moved from using the older DocSearch configuration (https://github.com/algolia/docsearch-website) to an Algolia account that Algolia provides to us for free. By default, the crawler for this is set ignore pages that have the robots meta set to `noindex`. I could update the crawler configuration to not ignore these pages.

(See https://github.com/timber/docs/blob/8db578510e31d693423075bc207a299dbd002374/_includes/html-head.njk#L21/. We set the robots meta to `noindex` so that the version 2 of the documentation doesn’t appear in search engine results yet.)
